export const GET_ARTICLES = 'GET_ARTICLES'
export const GET_ARTICLE = 'GET_ARTICLE'
export const RESET_ARTICLE = 'RESET_ARTICLE'
export const ADD_ARTICLE = 'ADD_ARTICLE'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_TAGS = 'GET_TAGS'
